### ISSUE TITLE
Problems with multiple same IDs

### ISSUE THREAD

**Issue by lhoracek** [vpedak/droidtestrec#18] opened 2016-04-01 11:46 UTC
I have layout that is using databinding and has multiple same components, that include EditText with same id (R.id.edit_value).
When recording the test, this ID is used in ViewMatcher, but then the test fails, because there are multiple view with same id in window.
Shouldn't recorder check, if the recorded ID is unique inside the window and if not, at least throw some warning? Best way would be switching to identifing by multiple IDs from parents (my current workaround)

**Comment by vpedak** [comment] 2016-04-04 08:48
@lhoracek Thanks a lot. I think this is very good idea. I will implement this, but maybe you can send me an example of your code to make sure that I will cover your use case (if this is possible)?

**Comment by lhoracek** [comment] 2016-04-04 09:32
Of course ;-)
I would love to have output like this:

```
// set username to test
onView(withId(R.id.username)).perform(scrollTo());
onView(allOf(withParent(withId(R.id.username)), withId(R.id.edit_value))).perform(replaceText("test_username"));
// set password to test
onView(withId(R.id.password)).perform(scrollTo());
onView(allOf(withParent(withId(R.id.password)), withId(R.id.edit_value))).perform(replaceText("test_password"));
```

You can see the edits have same ID, but different parent. They are just one xml included twice in different places. Databinding alows that component-like use.

**Comment by vpedak** [comment] 2016-04-05 12:40
@lhoracek is it possible for you to send me example of this Android activity with all those XMLs to save time for me to reproducing this?

**Comment by lhoracek** [comment] 2016-04-05 15:25
I will create sample code for you.

**Comment by lhoracek** [comment] 2016-04-05 22:35
Here is the example use-case https://github.com/lhoracek/databinding_includes

**Comment by vpedak** [comment] 2016-04-06 08:52
Thanks a lot!

**Comment by lhoracek** [comment] 2016-04-06 12:09
I will update the example with more use-cases. I came up with similar problem when using TabLayout with tabs that contain same IDs.

**Comment by vpedak** [comment] 2016-04-06 12:21
Thank you very much, this is helping me a lot.

**Comment by vpedak** [comment] 2016-04-07 09:14
@lhoracek I've uploaded new version 0.9.3 to the repository and to the site. Issue that you've reported should be fixed. Also I am using the generic approach so issue with TabLayout should be also fixed.

Can you please check this when you will have time? And thanks a lot for your idea and your help with this feature.

**Comment by lhoracek** [comment] 2016-04-07 16:04
Checking the 0.9.3 now and replace text generates the matcher perfectly:
`onView(allOf(withParent(withId(R.id.password)), withId(R.id.edit_value))).perform(replaceText("test"));`
but the same thing should be done for the scrollTo statement, generated to make members of scrollView visible.

Multiple same fragments inside ViewPager are still failing on AmbiguousViewMatcherException, but its more complicated here, as no parent ids could be available and child order could be different, as ViewPager removes children. Probably view Visibility as another matching rule could be used here with direct descendats of ViewPager. Will make more samples today hopefully so it is replicable and testable on something.

**Comment by vpedak** [comment] 2016-04-08 10:10
Yes, you are right. I've missed scroll to part. I've uploaded new version to site - http://droidtestlab.com/AndroidTestsRecorder.zip with this scrollTo fix. I will upload this fix to plugins repository at next release. So you can install plugin from file (site).

Also let me reopen issue because of ViewPager problems. If you will have ability to provide a sample I will try to resolve this somehow (in worse case I will create special Matcher). Thank you for your help.

**Comment by lhoracek** [comment] 2016-04-08 11:13
Will test later today and add ViewPager example. The ViewPager is working for me with the isDisplayed matcher:

```
     // Select page 2 in ViewPagerEx with id R.id.container
        onView(withId(R.id.container)).perform(selectViewPagerPage(2));

        // Click at LinearLayout with child index 1 of parent with id R.id.list
        onView(allOf(isDisplayed(),withId(R.id.list))).perform(scrollToPosition(1));
        onView(nthChildOf(allOf(isDisplayed(),withId(R.id.list)), 1)).perform(click());
```

**Comment by lhoracek** [comment] 2016-04-11 13:44
@vpedak Can confirm, that scroll to is correctly generated with parent path as well.

Viewpager stil causes problem, try utilising the above mentioned method with visibility (isDisplayed()).

**Comment by vpedak** [comment] 2016-04-11 15:09
@lhoracek ok, I will prepare a fix for Viewpager soon.

**Comment by vpedak** [comment] 2016-04-12 11:33
@lhoracek I've uploaded new version to the site http://droidtestlab.com/AndroidTestsRecorder.zip, it contains the fix for ViewPager. Can you please check it at your environment when you will have time?
And I will upload this version to Plugins Repository.

Thanks a lot for all your help with the project.

**Comment by vpedak** [comment] 2016-04-15 12:18
closing the issue, I've uploaded version 0.9.4 to the repository with all fixes related to this issue

**Closed as completed by vpedak** 2016-04-15 12:18 UTC
