### ISSUE TITLE
getInstrumentation() compiling error

### ISSUE THREAD

**Issue by leonard2014** [vpedak/droidtestrec#16] opened 2016-03-14 21:59 UTC
Last week I reinstalled Android Studio, after that there are getInstrumentation() compiling errors with the generated code. This is because **import static android.support.test.InstrumentationRegistry.*;**  is not declared in the source code. Could you add this line to the generated source code? Thanks!

**Comment by vpedak** [comment] 2016-03-15 08:51
It looks strange because `getInstrumentation()` is a public method of `InstrumentationTestCase` and my class extends `ActivityInstrumentationTestCase2` that extends  this `InstrumentationTestCase`.

What version of Android Studio and  Android Platform are you using? I will try to reproduce this.

**Comment by leonard2014** [comment] 2016-03-15 20:39
I am using Android Studio 1.5.1, 
gradle settings:

   compileSdkVersion 18
   buildToolsVersion "23.0.2"

   minSdkVersion 17
   targetSdkVersion 18 

Just checked the generated test case. It's like 

@RunWith(AndroidJUnit4.class)
@LargeTest
public class SessionActivityTest {
.......

}

It doesn't extend ActivityInstrumentationTestCase2

**Comment by vpedak** [comment] 2016-03-16 08:55
Sorry, I was thinking about another sources. Now I understand where was the issue. 
Thank you for details. It is fixed and will be available at next release.

**Comment by vpedak** [comment] 2016-04-07 09:14
Fixed in last release 0.9.3

**Closed as completed by vpedak** 2016-04-07 09:14 UTC
